### ISSUE TITLE
callback() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by xartin** [gkovacs/remove_miner_fees#1]
Found your script via ethermining subreddit and i've been trying to get it working with Gentoo. the 15 years i've been using gentoo leads me to believe i have all the dependencies installed this script should require.  
  
Tried using claymore's 9.4 and 9.5 with no change in error results.

dev-lang/python-2.7.12
net-libs/nfqueue-bindings-0.6
net-firewall/iptables-1.6.1-r1
net-analyzer/scapy-2.3.3  

scapy and nfqueue-bindings are both using python2.7 import paths.  

running Linux kernel 4.11.4

I'm not a wonderfully talented python coder but i see arg1, payload callback defined but for some reason that's escaped me two arguments are required.  

the print "" thing i added myself to see some more verbose callback function start feedback.

print "setting callback"
def callback(arg1, payload):
  data = payload.get_data()
  pkt = IP(data)

  payload_before = len(pkt[TCP].payload)

  payload_text = str(pkt[TCP].payload)
  for address_to_redirect in addresses_to_redirect:
    payload_text = address_to_redirect.sub(my_eth_address, payload_text)
  pkt[TCP].payload = payload_text

  payload_after = len(payload_text)

  payload_dif = payload_after - payload_before

  pkt[IP].len = pkt[IP].len + payload_dif

  pkt[IP].ttl = 40

  del pkt[IP].chksum
  del pkt[TCP].chksum
  payload.set_verdict_modified(nfqueue.NF_ACCEPT, str(pkt), len(pkt))
  logfile.write(payload_text)
  logfile.write('\n')
  logfile.flush()

# Error message
# ./remove_mining_fees.py
setting callback
callback failure !
TypeError: callback() takes exactly 2 arguments (1 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (1 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (1 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (1 given)
callback failure !
TypeError: callback() takes exactly 2 arguments (1 given)
^CStopping firewall and allowing everyone...

oh also. with regards to the restart_iptables script that's missing from the repo feel free to add this to satisfy the missing script. Perhaps a small contribution could be beneficial here 
  
#!/bin/bash
echo "Stopping firewall and allowing everyone..."
ipt="/sbin/iptables"
## Failsafe - die if /sbin/iptables not found
[ ! -x "$ipt" ] && { echo "$0: \"${ipt}\" command not found."; exit 1; }
$ipt -P INPUT ACCEPT
$ipt -P FORWARD ACCEPT
$ipt -P OUTPUT ACCEPT
$ipt -F
$ipt -X
$ipt -t nat -F
$ipt -t nat -X
$ipt -t mangle -F
$ipt -t mangle -X
$ipt -t raw -F
$ipt -t raw -X

**Comment by zerf2004** [comment]
I am getting this error when I try to run the script. Any ideas?

```
callback failure !
Traceback (most recent call last):
  File "remove_mining_fees.py", line 76, in callback
    payload.set_verdict_modified(nfqueue.NF_ACCEPT, str(pkt), len(pkt))
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 340, in do_build
    self = self.__iter__().next()
StopIteration
```

**Comment by xartin** [comment]
Just a small update...

I did manage to get this script working running in a ubuntu server virtual machine but it wouldn't work in gentoo.  
  
i suspect ubuntu has some "feature" enabled in their python 2.7 build that Gentoo doesn't or vice versa. Strange considering Gentoo ships every system with python ad a hardcoded core system dependency.  
  
Will have to investigate this in more detail in the near future with the gentoo python developers.

**Comment by zerf2004** [comment]
@xartin I am trying to get the ubuntu server method setup. What do I need to run on the miner PC to get it to send the traffic to the server?

**Comment by xartin** [comment]
@zerf2004 change the default gateway for the miner pc to the ubuntu server secondary network interface.  
  
I assume you added a second network interface as well if your using vmware or virtualbox to host the ubuntu server. Naturally you will need to adjust the iptables rules to the interface names for your ubuntu server.

Also ensure you have ipv4 forwarding enabled in /etc/sysctl.conf

**Comment by zerf2004** [comment]
@xartin , I was able to change the default GW on the miner pc to my 2nd nic on the server.(physical box not vm) and I saw the traffic coming in/out on the server when looking at iptables -L -n -v but I was still getting the same error below. It is a fresh build of ubuntu server 16.04 LTS. Anyway I could contact you by some other means than on here?

`AttributeError: 'str' object has no attribute 'build_padding'
callback failure !
Traceback (most recent call last):
  File "remove_mining_fees.py", line 78, in callback
    payload.set_verdict_modified(nfqueue.NF_ACCEPT, str(pkt), len(pkt))
  File "/home/miner/.local/lib/python2.7/site-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/home/miner/.local/lib/python2.7/site-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/home/miner/.local/lib/python2.7/site-packages/scapy/packet.py", line 340, in do_build
    self = self.__iter__().next()
StopIteration
`

**Comment by gkovacs** [comment]
oh yes I'm using nfqueue 0.5-1build2 (the version for xenial in ubuntu's repositories) I think 0.8 has a different signature, I think if you modify the callback and add a dummy argument at the first position it should fix the issue

**Comment by zerf2004** [comment]
@gkovacs  I am using the same nfqueue as you and still getting the error below . Any other ideas?
`python-nfqueue/xenial,now 0.5-1build2 amd64 [installed]`

`callback failure !
Traceback (most recent call last):
  File "remove_mining_fees.py", line 76, in callback
    payload.set_verdict_modified(nfqueue.NF_ACCEPT, str(pkt), len(pkt))
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 277, in __str__
    return self.build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 354, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 340, in do_build
    self = self.__iter__().next()
StopIteration`

**Comment by gkovacs** [comment]
also check the version of python-scapy? I'm using 2.2.0-1

**Comment by zerf2004** [comment]
Switching from 2.3.3 to 2.2.0.dev0 did it! It seems to be running now! No errors like before at least! Thanks for the info. Might want to put that stuff in the readme.

**Comment by KHouse75** [comment]
callback has 2 arguments defined, arg1 and payload.  The call to callback only uses 1 argument.  Since arg1 is not used, remove arg1 to resolve the problem.

Before:
    def callback(arg1, payload):

After:
   def callback(payload):
